monolog:
    handlers:
        # this "file_log" key could be anything
        file_log:
            type: stream
            # log to var/log/(environment).log
            path: "%kernel.logs_dir%/sync.log"
            # log *all* messages (debug is lowest level)
            level: debug
            formatter: App\Messages\Logger\Formatter
            channels: ["!event", "!doctrine", "!php", "!request"]

        #syslog_handler:
        #    type: syslog
            # log error-level messages and higher
        #    level: error