FROM php:7.2-fpm-alpine

# MySQL
RUN \
    docker-php-ext-install pdo pdo_mysql

# XDebug
RUN \
    apk --no-cache add --virtual .build-deps $PHPIZE_DEPS && \
    pecl install xdebug-2.6.0 && \
    docker-php-ext-enable xdebug && \
    apk del .build-deps
